### ISSUE TITLE
I don't have time

### ISSUE THREAD

**Issue by pjztam** [pjztam/Team766-Attendance#36]
Well basically, College is hard. Classes are difficult, homework is complicated, and I don't have time anymore for this project. The biggest problem, however, is that I use my free time socializing instead of staying in my room programming. I guess this project is now on indefinite hiatus, until I find time for this project again.

**Comment by blevenson** [comment]
Wow!  What kind of loser would want to socialize in their free time, instead of staying in their dorm programming?

**Comment by pjztam** [comment]
Thanks Brett.
