### ISSUE TITLE
Log off button

### ISSUE THREAD

**Issue by blevenson** [pjztam/Team766-Attendance#39]
Due to security issues that arose from people sharing the password to the attendance website and people going onto the laptops that have already been signed into the website, it has become necessary to add a log off button, that would sign you off the team766 user system.  Then when that computer would like to regain access, they simple have to reenter their username(team766) and password(•••••).

**Comment by pjztam** [comment]
wow maybe you guys shouldn't share the password then

**Comment by blevenson** [comment]
Then maybe the password shouldn't be something people can easily rember. Or another thought is to not invite everyone to the password doc that asks...  Patrick.

**Comment by pjztam** [comment]
Do you want to type a really complicated password every meeting? I didn't think so. Also, the people on the doc are hopefully reasonable enough to not abuse the password.
